@extends('layout')
@section('css')
    <link href="{{ asset('base/style.bundle.css') }}" rel="stylesheet">
@endsection
@section('content')
    <div class="m-subheader ">
        <div class="align-items-center">
            <div class="mr-auto">
                <h3 class="m-subheader__title m-subheader__title--separator">
                    Human Resource
                </h3>
                <div style="    float: right;padding: 5px 0px 0px 0px;">
                    <input style="    width: 277px; border: none;border-radius: 72px;padding: 5px 7px 5px 7px;"
                           type="search" name="search" placeholder="Search">
                </div>
            </div>

        </div>
    </div>
    <br>
    <div class="m-content">
        <div class="m-portlet">
            <div class="m-portlet__head">
                <div class="m-portlet__head-caption">
                    <div class="m-portlet__head-title">
                        <!-- <span class="m-portlet__head-icon">
                            <i class="flaticon-users"></i>
                        </span> -->
                        <h3 class="m-portlet__head-text">
                            Salary Slip
                        </h3>

                    </div>
                </div>
            </div>
            <div class="m-portlet__body">
                <center style="padding-top: 15px">
                    <form id="month_ch">
                        <input value="{{date('Y-m', strtotime($start_month))}}" type="month" name="month_year"
                               onchange="$('#month_ch').submit()">

                    </form>
                    <small>
                        {{date_to_str($start_month)}} to {{date_to_str($end_month)}}
                    </small>

                </center>
                <div class="salary_slip" id="printJS-form">

                    <center>
                        <div class="row" style="padding-top: 50px">
                            <div class="col-md-12 row">
                                <div class="col-md-12" style="text-align: center;">
                                    <h3>{{$company->company_name}}</h3>
                                    <span>{{$company->address}}</span>
                                    <br>
                                    <span>{{$company->phone}}</span>
                                </div>
                            </div>
                        </div>
                    </center>

                    <table class="slip_pay">
                        <tbody class="slip_pay">
                        <tr class="slip_pay">
                            <td class="slip_pay custom_td"><h1 class="slip_pay custom_heading">Payslip</h1></td>
                            <td class="slip_pay tdMiddle">
                                <p class="box slip_pay">
                                    <span class="slip_pay boxHead ">Month of salary:</span><br/>
                                    <span class="slip_pay boxContent ">{{date('M-Y', strtotime($start_month))}}</span>
                                </p>
                            </td>
                            <td class="slip_pay tdMiddle">
                                <p class=" box slip_pay">
                                    <span class="slip_pay boxHead">Printed date:</span><br/>
                                    <span class=" slip_pay boxContent ">{{date_to_str(date('Y-m-d'))}}</span>
                                </p>
                            </td>
                            {{-- <td class="tdSmall slip_pay">
                                <p class="box slip_pay">
                                    <span class="boxHead slip_pay">Generated by:</span><br />
                                    <span class="boxContent slip_pay">7</span>
                                </p>
                            </td> --}}
                        </tr>
                        </tbody>
                    </table>
                    <p class="subHead slip_pay">Considered as income receipt. Please store it carefully.</p>

                    <table class="slip_pay" style="margin-top: 15px;">
                        <tbody class="slip_pay">
                        <tr class="slip_pay">
                            <td id="address" class="slip_pay">
                                <p id="addressCompany" class="slip_pay">Employee's Detail</p>
                                <p id="addressEmployee" class="slip_pay">
                                    Employee #{{$employee->id}}<br>
                                    {{$employee->name}}<br>
                                    {{$employee->position}}<br>
                                    {{$employee->address}}<br>
                                    {{$employee->phone}}<br>
                                </p>
                            </td>
                            <td id="employeeExtraFields" class="slip_pay">
                                <table class="slip_pay">
                                    <tbody class="slip_pay">
                                    <tr class="slip_pay">
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Pay Slip #:</span><br/>
                                                <span class="boxContent slip_pay">{{date('Ym', strtotime($start_month))}}-{{$employee->id}}</span>
                                            </p>

                                        </td>
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Type:</span><br/>
                                                <span class="boxContent slip_pay">{{$employee->billing_type}}</span>
                                            </p>

                                        </td>
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Generated:</span><br/>
                                                <span class="boxContent slip_pay">{{auth()->user()->name}}</span>
                                            </p>

                                        </td>

                                    </tr>
                                    <tr class="slip_pay">
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Attendance:</span><br/>
                                                <span class="boxContent slip_pay">{{$total_days_worked}} [{{number_format($attendance_hours)}} hrs]</span>
                                            </p>

                                        </td>
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Paid Leaves:</span><br/>
                                                <span class="boxContent slip_pay">{{$leaves}}</span>
                                            </p>

                                        </td>
                                        <td class="slip_pay">
                                            <p class="box slip_pay">
                                                <span class="boxHead slip_pay">Holidays:</span><br/>
                                                <span class="boxContent slip_pay">{{$holidays}}</span>
                                            </p>

                                        </td>

                                    </tr>

                                    </tbody>
                                </table>
                            </td>
                        </tr>

                        </tbody>
                    </table>

                    <h6 style="margin-top: 30px;">Remarks</h6>
                    <p>
                        <textarea rows="1" style="border: 1px solid; resize: none; width:100%"
                                  placeholder="Reason for Absent"></textarea><br/>
                    </p>


                    <div class="sal_details" style="border: 1px solid;margin-top: 20px;">
                        <div class="sal_details_heading" style="padding: 10px 15px 7px 15px;">
                            <h3>Salary Details</h3>
                        </div>
                        <div class="sal_details_body">
                            <table style="width: 100%;">
                                <thead style="border-top:1px solid;border-bottom:1px solid">
                                <tr style="text-align: center;">
                                    <th style="border-right: 1px solid;width: 50%">Earning</th>
                                    <th>Deduction</th>
                                </tr>
                                </thead>
                                <tbody>
                                <tr>
                                    <td style="border-right:1px solid">
                                        <table style="width: 100%;">
                                            <thead style="border-bottom: 1px solid">
                                            <tr>
                                                <th style="border-right: 1px solid;text-align: center;">Salary logs</th>
                                                <th style="text-align: center;">Amount</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td style="border-right: 1px solid;text-align: center;">Basic Salary
                                                </td>
                                                <td style="text-align: center;">{{number_format($salary)}}</td>
                                            </tr>
                                            @if ($overtimeamount > 0)
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">Over-time
                                                        <br>
                                                        @if($employee->billing_type == "per_hour")
                                                            ({{number_format($overtime,2)}}-hrs)
                                                        @else
                                                        ({{number_format($overtime,0)}}-days)
                                                        @endif
                                                    </td>
                                                    <td style="text-align: center;">{{number_format($overtimeamount)}}</td>
                                                </tr>
                                            @else
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">-</td>
                                                    <td style=" solid;text-align: center;">-</td>
                                                </tr>
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">-</td>
                                                    <td style=" solid;text-align: center;">-</td>
                                                </tr>

                                            @endif

                                            @if (!$total_bonus)
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            @else
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">
                                                        <!-- <ul> -->

                                                        <table class="table table-bordered">
                                                            <thead>
                                                            <th>Description</th>
                                                            <th>Amount</th>
                                                            </thead>
                                                            <tbody>
                                                            @foreach(get_bonus($id,$start_month,$end_month) as $bonus)
                                                                <tr>
                                                                    <td>{{$bonus->description}} </td>
                                                                    <td>{{number_format($bonus->bonus)}}</td>
                                                                </tr>
                                                            @endforeach
                                                            </tbody>
                                                        </table>
                                                        <!-- </ul> -->
                                                        Total Bonus
                                                    </td>
                                                    <td style="text-align: center;">{{number_format($total_bonus)}}</td>
                                                </tr>
                                            @endif

                                            </tbody>
                                            <tfoot style="border-top: 1px solid">
                                            <tr>
                                                <th style="border-right: 1px solid;text-align: center;">Total Amount
                                                </th>
                                                <th style="text-align: center;">{{number_format($salary + $overtimeamount + $total_bonus)}}</th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                    </td>
                                    <td>
                                        <table style="width: 100%;">
                                            <thead style="border-bottom: 1px solid">
                                            <tr>
                                                <th style="border-right: 1px solid;text-align: center;">Salary logs</th>
                                                <th style="text-align: center;">Amount</th>
                                            </tr>
                                            </thead>
                                            <tbody>
                                            <tr>
                                                <td style="border-right: 1px solid;text-align: center;">Absent
                                                    <br>({{$absent}} Days)
                                                </td>
                                                <td style="text-align: center;">{{number_format($absent_amount)}}</td>
                                            </tr>

                                            @if($employee->billing_type == "per_hour")
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">Time lag
                                                        amount <br>({{$time_lag}}-hrs)
                                                    </td>
                                                    <td style="text-align: center;">{{number_format($time_lag_amount)}}</td>
                                                </tr>
                                            @else
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">-</td>
                                                    <td style="text-align: center;">-</td>
                                                </tr>
                                            @endif
                                            @if (!$total_deduction)
                                                <tr>
                                                    <td></td>
                                                    <td></td>
                                                </tr>
                                            @else
                                                <tr>
                                                    <td style="border-right: 1px solid;text-align: center;">
                                                        <table class="table table-bordered">
                                                            <thead>
                                                            <th>Description</th>
                                                            <th>Amount</th>
                                                            </thead>
                                                            <tbody>
                                                            @foreach(get_bonus($id,$start_month,$end_month,true) as $bonus)
                                                                <tr>
                                                                    <td>{{$bonus->description}} </td>
                                                                    <td>{{number_format($bonus->bonus)}}</td>
                                                                </tr>
                                                            @endforeach
                                                            </tbody>
                                                        </table>
                                                        Total Deductions
                                                    </td>
                                                    <td style="text-align: center;">{{number_format($total_deduction)}}</td>
                                                </tr>
                                            @endif


                                            </tbody>
                                            <tfoot style="border-top: 1px solid">
                                            <tr>
                                                <th style="border-right: 1px solid;text-align: center;">Total Amount
                                                </th>
                                                <th style="text-align: center;">{{number_format($time_lag_amount+$absent_amount+$total_deduction)}}</th>
                                            </tr>
                                            </tfoot>
                                        </table>
                                </tr>

                                </tbody>
                                <tfoot style="border-top: 1px solid;line-height: 4;background: black;color: white;">
                                <tr>
                                    <th style="border-right: 1px solid;text-align: center;border-top: 1px solid">Net
                                        Total
                                    </th>
                                    <th style="text-align: center;border-top:1px solid">
                                        Rs.{{number_format($total_computed_salary)}}/-<br>{{$salary_in_words}} only
                                    </th>
                                </tr>
                                </tfoot>

                            </table>
                        </div>
                    </div>


                    <table class="slip_pay" style="margin-top: 20px;border-top: 0px">
                        <tbody class="slip_pay">
                        <tr class="slip_pay">
                            <td class="slip_pay tdMiddle">
                                <h6>{{env('MANAGER_NAME_SALARY')}}</h6>
                                <p class="slip_pay box">
                                    <span class="slip_pay boxHead">Manager Signature:</span><br/>
                                    <span class="slip_pay boxContent"></span>
                                </p>
                            </td>
                            <td class="slip_pay">

                                <h6>{{env('DIRECTOR_NAME_SALARY')}}</h6>
                                <p class="box slip_pay">
                                    <span class="boxHead slip_pay">Director Signature:</span><br/>
                                    <span class="boxContent slip_pay"></span>
                                </p>
                            </td>
                        </tr>
                        </tbody>
                    </table>


                </div>

                <button type="button" class="btn btn-success m-btn m-btn--custom m-btn--icon m-btn--pill"
                        style="margin-top: 55px;" onclick="printJS('printJS-form', 'html')">Print Salary
                </button>
                <button type="button" data-toggle="modal" data-target="#m_modal_5"
                        class="btn btn-info m-btn m-btn--custom m-btn--icon m-btn--pill" style="margin-top: 55px;">
                    Payment Release
                </button>

            </div>


        </div>
    </div>
    {{-- model for payment --}}
    <div class="modal fade" id="m_modal_5" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Payment</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form role="form" method="POST" action="{{url('/hr/salary')."/".$employee->id."/pay"}}">
                        <input type="hidden" name="_token" value="{{ csrf_token() }}">
                        <input type="hidden" name="userid" value="{{Auth::id()}}">

                        <div class="form-group">
                            <label for="message-text" class="form-control-label">Pay as:</label>
                            <input type='text' class='form-control' value='Monthly Salary' readonly>
                        </div>
                        <div class="form-group" id="milgu">
                            <label for="message-text" class="form-control-label">Amount in pkr(monthly):</label>
                            <input type='text' class='form-control' value='{{$total_computed_salary}}' name="amount"
                                   readonly>
                        </div>

                        <div class="form-group">
                            <label for="message-text" class="form-control-label">Release amount:</label>
                            <input type='text' class='form-control' name="amountrelease" value="0"
                                   placeholder="amount to be released">
                        </div>

                        <div class="form-group" id="gilmu">
                            <label for="message-text" class="form-control-label">Date:</label>
                            <input type='date' class='form-control' value='{{date('Y-m-d', strtotime($start_month))}}'
                                   name="date">
                        </div>

                        <div class="form-group">
                            <label for="recipient-name" class="form-control-label">Status:</label>
                            {{-- <input type="text" class="form-control" id="recipient-name"> --}}
                            <select class="form-control" name="status">
                                <option value="paid">paid</option>
                                <option value="unpaid" selected>unpaid</option>
                                <option value="cancelled">cancelled</option>
                            </select>
                        </div>

                        <div class="modal-footer">
                            <button type="reset" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {{-- model for payment ends --}}
@endsection
@section('scripts')
    <script>
        $("title").html("Salary Calculation - ID:{{$employee->id}} {{$employee->name}} {{date('M-Y', strtotime($start_month))}}");
    </script>
@endsection